DROP USER D02;

CREATE USER D02;

CREATE SEQUENCE D02SQD49_NSUMGRCO;

CREATE SEQUENCE D02SQP01_OCRNA;

CREATE TABLE D02TBP01_PRMOPRPRE (
   NU_PRODUTO_P20       INT2                 NOT NULL,
   NU_PRPRE_PRDTO_P20   INT2                 NOT NULL,
   NU_TIPO_PRMTO_P03    INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP01_PRMOPRPRE owner to D02
;
ALTER TABLE D02TBP01_PRMOPRPRE
   ADD CONSTRAINT D02PKP01 PRIMARY KEY (NU_PRODUTO_P20, NU_PRPRE_PRDTO_P20, NU_TIPO_PRMTO_P03);

CREATE UNIQUE INDEX D021IP01 ON D02TBP01_PRMOPRPRE (
NU_PRODUTO_P20,
NU_PRPRE_PRDTO_P20,
NU_TIPO_PRMTO_P03
);

CREATE TABLE D02TBP02_TIPOPRMTO (
   NU_TIPO_PARAMETRO    INT2                 NOT NULL,
   NO_TIPO_PARAMETRO    CHAR(200)            NOT NULL,
   IC_TIPO_PARAMETRO    CHAR(1)              NOT NULL
);

-- set table ownership
alter table D02TBP02_TIPOPRMTO owner to D02
;
ALTER TABLE D02TBP02_TIPOPRMTO
   ADD CONSTRAINT D02PKP02 PRIMARY KEY (NU_TIPO_PARAMETRO);

CREATE UNIQUE INDEX D021IP02 ON D02TBP02_TIPOPRMTO (
NU_TIPO_PARAMETRO
);

CREATE TABLE D02TBP03_PRMOPRDTO (
   NU_PRODUTO_P53       INT2                 NOT NULL,
   NU_TIPO_PRMTO_P02    INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP03_PRMOPRDTO owner to D02
;
ALTER TABLE D02TBP03_PRMOPRDTO
   ADD CONSTRAINT D02PKP03 PRIMARY KEY (NU_PRODUTO_P53, NU_TIPO_PRMTO_P02);

CREATE UNIQUE INDEX D021IP03 ON D02TBP03_PRMOPRDTO (
NU_PRODUTO_P53,
NU_TIPO_PRMTO_P02
);

CREATE TABLE D02TBP04_GRPOCMNDO (
   NU_GRUPO_COMANDO     INT2                 NOT NULL,
   NO_GRUPO_COMANDO     VARCHAR(40)          NOT NULL
);

-- set table ownership
alter table D02TBP04_GRPOCMNDO owner to D02
;
ALTER TABLE D02TBP04_GRPOCMNDO
   ADD CONSTRAINT D02PKP04 PRIMARY KEY (NU_GRUPO_COMANDO);

CREATE UNIQUE INDEX D021IP04 ON D02TBP04_GRPOCMNDO (
NU_GRUPO_COMANDO
);

CREATE TABLE D02TBP05_SBGOCMNDO (
   NU_SUBGRUPO_CMNDO    INT2                 NOT NULL,
   NO_SUBGRUPO_CMNDO    VARCHAR(40)          NOT NULL
);

-- set table ownership
alter table D02TBP05_SBGOCMNDO owner to D02
;
ALTER TABLE D02TBP05_SBGOCMNDO
   ADD CONSTRAINT D02PKP05 PRIMARY KEY (NU_SUBGRUPO_CMNDO);

CREATE UNIQUE INDEX D021IP05 ON D02TBP05_SBGOCMNDO (
NU_SUBGRUPO_CMNDO
);

CREATE TABLE D02TBP06_GRSBCMNDO (
   NU_GRUPO_CMNDO_P04   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P05   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP06_GRSBCMNDO owner to D02
;
ALTER TABLE D02TBP06_GRSBCMNDO
   ADD CONSTRAINT D02PKP06 PRIMARY KEY (NU_GRUPO_CMNDO_P04, NU_SBGRO_CMNDO_P05);

CREATE UNIQUE INDEX D021IP06 ON D02TBP06_GRSBCMNDO (
NU_GRUPO_CMNDO_P04,
NU_SBGRO_CMNDO_P05
);

CREATE TABLE D02TBP07_TIPOCMNDO (
   NU_TIPO_COMANDO      INT2                 NOT NULL,
   NO_TIPO_COMANDO      VARCHAR(40)          NOT NULL
);

-- set table ownership
alter table D02TBP07_TIPOCMNDO owner to D02
;
ALTER TABLE D02TBP07_TIPOCMNDO
   ADD CONSTRAINT D02PKP07 PRIMARY KEY (NU_TIPO_COMANDO);

CREATE UNIQUE INDEX D021IP07 ON D02TBP07_TIPOCMNDO (
NU_TIPO_COMANDO
);

CREATE TABLE D02TBP08_SBTOCMNDO (
   NU_SUBTIPO_COMANDO   INT2                 NOT NULL,
   NO_SUBTIPO_COMANDO   VARCHAR(40)          NOT NULL
);

-- set table ownership
alter table D02TBP08_SBTOCMNDO owner to D02
;
ALTER TABLE D02TBP08_SBTOCMNDO
   ADD CONSTRAINT D02PKP08 PRIMARY KEY (NU_SUBTIPO_COMANDO);

CREATE UNIQUE INDEX D021IP08 ON D02TBP08_SBTOCMNDO (
NU_SUBTIPO_COMANDO
);

CREATE TABLE D02TBP09_TPSBCMNDO (
   NU_TIPO_CMNDO_P07    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P08   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP09_TPSBCMNDO owner to D02
;
ALTER TABLE D02TBP09_TPSBCMNDO
   ADD CONSTRAINT D02PKP09 PRIMARY KEY (NU_TIPO_CMNDO_P07, NU_SBTPO_CMNDO_P08);

CREATE UNIQUE INDEX D021IP09 ON D02TBP09_TPSBCMNDO (
NU_TIPO_CMNDO_P07,
NU_SBTPO_CMNDO_P08
);

CREATE TABLE D02TBP10_COMANDO (
   NU_GRUPO_CMNDO_P06   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P06   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P09    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P09   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP10_COMANDO owner to D02
;
ALTER TABLE D02TBP10_COMANDO
   ADD CONSTRAINT D02PKP10 PRIMARY KEY (NU_GRUPO_CMNDO_P06, NU_SBGRO_CMNDO_P06, NU_TIPO_CMNDO_P09, NU_SBTPO_CMNDO_P09);

CREATE UNIQUE INDEX D021IP10 ON D02TBP10_COMANDO (
NU_GRUPO_CMNDO_P06,
NU_SBGRO_CMNDO_P06,
NU_TIPO_CMNDO_P09,
NU_SBTPO_CMNDO_P09
);

CREATE TABLE D02TBP11_ACAOTRNSO (
   NU_ACAO_TRANSACAO    INT2                 NOT NULL,
   NO_ACAO_TRANSACAO    VARCHAR(40)          NOT NULL,
   DE_ACAO_TRANSACAO    CHAR(100)            NULL
);

-- set table ownership
alter table D02TBP11_ACAOTRNSO owner to D02
;
ALTER TABLE D02TBP11_ACAOTRNSO
   ADD CONSTRAINT D02PKP11 PRIMARY KEY (NU_ACAO_TRANSACAO);

CREATE UNIQUE INDEX D021IP11 ON D02TBP11_ACAOTRNSO (
NU_ACAO_TRANSACAO
);

CREATE TABLE D02TBP12_MODOTRNSO (
   NU_MODO_TRANSACAO    INT2                 NOT NULL,
   NO_MODO_TRANSACAO    VARCHAR(40)          NOT NULL,
   DE_MODO_TRANSACAO    CHAR(200)            NULL
);

-- set table ownership
alter table D02TBP12_MODOTRNSO owner to D02
;
ALTER TABLE D02TBP12_MODOTRNSO
   ADD CONSTRAINT D02PKP12 PRIMARY KEY (NU_MODO_TRANSACAO);

CREATE UNIQUE INDEX D021IP12 ON D02TBP12_MODOTRNSO (
NU_MODO_TRANSACAO
);

CREATE TABLE D02TBP13_ACMDTRNSO (
   NU_ACAO_TRNSO_P11    INT2                 NOT NULL,
   NU_MODO_TRNSO_P12    INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP13_ACMDTRNSO owner to D02
;
ALTER TABLE D02TBP13_ACMDTRNSO
   ADD CONSTRAINT D02PKP13 PRIMARY KEY (NU_ACAO_TRNSO_P11, NU_MODO_TRNSO_P12);

CREATE UNIQUE INDEX D021IP13 ON D02TBP13_ACMDTRNSO (
NU_ACAO_TRNSO_P11,
NU_MODO_TRNSO_P12
);

CREATE TABLE D02TBP14_ACMDGRPO (
   NU_ACAO_TRNSO_P13    INT2                 NOT NULL,
   NU_MODO_TRNSO_P13    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P04   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP14_ACMDGRPO owner to D02
;
ALTER TABLE D02TBP14_ACMDGRPO
   ADD CONSTRAINT D02PKP14 PRIMARY KEY (NU_ACAO_TRNSO_P13, NU_MODO_TRNSO_P13, NU_GRUPO_CMNDO_P04);

CREATE UNIQUE INDEX D021IP14 ON D02TBP14_ACMDGRPO (
NU_ACAO_TRNSO_P13,
NU_MODO_TRNSO_P13,
NU_GRUPO_CMNDO_P04
);

CREATE TABLE D02TBP15_CIF (
   NU_ACAO_TRNSO_P14    INT2                 NOT NULL,
   NU_MODO_TRNSO_P14    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P10   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P10   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P10    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P10   INT2                 NOT NULL,
   NO_CIF               VARCHAR(60)          NOT NULL,
   NO_ABRVO_CIF         CHAR(25)             NOT NULL,
   DT_CRIACAO_CIF       DATE                 NOT NULL,
   IC_SITUACAO_CIF      CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   TS_ALTERACAO_CIF     DATE                 NOT NULL,
   DT_INICIO_VIGENCIA   DATE                 NOT NULL,
   NO_REDUZIDO_CIF      CHAR(10)             NOT NULL,
   VR_CUSTO_PRCSO       DECIMAL(5,2)         NULL,
   DT_FIM_VIGENCIA      DATE                 NULL,
   DE_MOTIVO_STCO_CIF   VARCHAR(40)          NULL,
   NU_PRIORIDADE_P55    INT2                 NULL,
   IC_MVMNO_ESPTA       CHAR(1)              NOT NULL,
   NU_FNCNE_ESPCL_P21   INT2                 NULL,
   IC_PENDENCIA         CHAR(1)              NOT NULL DEFAULT 'N',
   IC_TIPO_EXTRACAO     CHAR(1)              NOT NULL DEFAULT 'N'
);

-- set table ownership
alter table D02TBP15_CIF owner to D02
;
ALTER TABLE D02TBP15_CIF
   ADD CONSTRAINT D02PKP15 PRIMARY KEY (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10);

CREATE UNIQUE INDEX D021IP15 ON D02TBP15_CIF (
NU_ACAO_TRNSO_P14,
NU_MODO_TRNSO_P14,
NU_GRUPO_CMNDO_P10,
NU_SBGRO_CMNDO_P10,
NU_TIPO_CMNDO_P10,
NU_SBTPO_CMNDO_P10
);

CREATE TABLE D02TBP16_CIFPRPRE (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_PRODUTO_P20       INT2                 NOT NULL,
   NU_PRPRE_PRDTO_P20   INT2                 NOT NULL,
   IC_STCO_CIF_PRPRE    CHAR(1)              NOT NULL,
   DE_MOTIVO_SITUACAO   CHAR(60)             NULL
);

-- set table ownership
alter table D02TBP16_CIFPRPRE owner to D02
;
ALTER TABLE D02TBP16_CIFPRPRE
   ADD CONSTRAINT D02PKP16 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_PRODUTO_P20, NU_PRPRE_PRDTO_P20);

CREATE UNIQUE INDEX D021IP16 ON D02TBP16_CIFPRPRE (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_PRODUTO_P20,
NU_PRPRE_PRDTO_P20
);

CREATE TABLE D02TBP17_ATRIBUTO (
   NU_ATRIBUTO          INT2                 NOT NULL,
   NO_ATRIBUTO          VARCHAR(60)          NOT NULL,
   DE_ATRIBUTO          VARCHAR(255)         NULL
);

-- set table ownership
alter table D02TBP17_ATRIBUTO owner to D02
;
ALTER TABLE D02TBP17_ATRIBUTO
   ADD CONSTRAINT D02PKP17 PRIMARY KEY (NU_ATRIBUTO);

CREATE UNIQUE INDEX D021IP17 ON D02TBP17_ATRIBUTO (
NU_ATRIBUTO
);

CREATE TABLE D02TBP18_CIFATRBO (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_ATRIBUTO_P19      INT2                 NOT NULL,
   IC_OBRGE_ATRIBUTO    INT2                 NOT NULL,
   DE_REGRA_ATRTO_CIF   VARCHAR(255)         NULL
);

-- set table ownership
alter table D02TBP18_CIFATRBO owner to D02
;
ALTER TABLE D02TBP18_CIFATRBO
   ADD CONSTRAINT D02PKP18 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_ATRIBUTO_P19);

CREATE UNIQUE INDEX D021IP18 ON D02TBP18_CIFATRBO (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_ATRIBUTO_P19
);

CREATE TABLE D02TBP19_GRPOATRBO (
   NU_GRUPO_CMNDO_P04   INT2                 NOT NULL,
   NU_ATRIBUTO_P17      INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP19_GRPOATRBO owner to D02
;
ALTER TABLE D02TBP19_GRPOATRBO
   ADD CONSTRAINT D02PKP19 PRIMARY KEY (NU_GRUPO_CMNDO_P04, NU_ATRIBUTO_P17);

CREATE UNIQUE INDEX D021IP19 ON D02TBP19_GRPOATRBO (
NU_GRUPO_CMNDO_P04,
NU_ATRIBUTO_P17
);

CREATE TABLE D02TBP20_PRPREDSTO (
   NU_PRODUTO_O28       INT2                 NOT NULL,
   NU_PRPRE_PRDTO_O28   INT2                 NOT NULL,
   IC_STCO_PRPRE_DSTO   CHAR(1)              NOT NULL,
   DT_CRCO_PRPRE_DSTO   DATE                 NOT NULL
);

-- set table ownership
alter table D02TBP20_PRPREDSTO owner to D02
;
ALTER TABLE D02TBP20_PRPREDSTO
   ADD CONSTRAINT D02PKP20 PRIMARY KEY (NU_PRODUTO_O28, NU_PRPRE_PRDTO_O28);

CREATE UNIQUE INDEX D021IP20 ON D02TBP20_PRPREDSTO (
NU_PRODUTO_O28,
NU_PRPRE_PRDTO_O28
);

CREATE TABLE D02TBP21_FNCEESPCL (
   NU_FNCNE_ESPECIAL    INT2                 NOT NULL,
   NO_FNCNE_ESPECIAL    VARCHAR(60)          NOT NULL,
   SG_FNCNE_ESPECIAL    CHAR(3)              NOT NULL,
   IC_STCO_FCNE_ESPCL   CHAR(1)              NOT NULL
);

-- set table ownership
alter table D02TBP21_FNCEESPCL owner to D02
;
ALTER TABLE D02TBP21_FNCEESPCL
   ADD CONSTRAINT D02PKP21 PRIMARY KEY (NU_FNCNE_ESPECIAL);

CREATE UNIQUE INDEX D021IP21 ON D02TBP21_FNCEESPCL (
NU_FNCNE_ESPECIAL
);

CREATE TABLE D02TBP22_TPMSGMSSA (
   CO_TPO_MNSGM_SSTMA   CHAR(2)              NOT NULL,
   NO_TPO_MNSGM_SSTMA   CHAR(20)             NOT NULL
);

-- set table ownership
alter table D02TBP22_TPMSGMSSA owner to D02
;
ALTER TABLE D02TBP22_TPMSGMSSA
   ADD CONSTRAINT D02PKP22 PRIMARY KEY (CO_TPO_MNSGM_SSTMA);

CREATE UNIQUE INDEX D021IP22 ON D02TBP22_TPMSGMSSA (
CO_TPO_MNSGM_SSTMA
);

CREATE TABLE D02TBP23_MSGMSSTMA (
   CO_TPO_MSG_SSA_P22   CHAR(2)              NOT NULL,
   NU_MNSGM_SISTEMA     INT2                 NOT NULL,
   DE_MNSGM_SISTEMA     VARCHAR(200)         NOT NULL,
   IC_CNDCO_MENSAGEM    INT2                 NOT NULL,
   IC_STCO_MSGM_SSTMA   CHAR(1)              NOT NULL,
   DE_MNSGM_RESUMIDA    CHAR(20)             NULL,
   CO_RETORNO_ISO       CHAR(2)              NULL
);

-- set table ownership
alter table D02TBP23_MSGMSSTMA owner to D02
;
ALTER TABLE D02TBP23_MSGMSSTMA
   ADD CONSTRAINT D02PKP23 PRIMARY KEY (CO_TPO_MSG_SSA_P22, NU_MNSGM_SISTEMA);

CREATE UNIQUE INDEX D021IP23 ON D02TBP23_MSGMSSTMA (
CO_TPO_MSG_SSA_P22,
NU_MNSGM_SISTEMA
);

CREATE TABLE D02TBP24_PRMOSSTMA (
   NU_SGMNO_ORGM_S12    INT2                 NOT NULL,
   IC_FORMA_TRANSACAO   CHAR(1)              NOT NULL,
   IC_SITUACAO_SSTMA    CHAR(1)              NOT NULL,
   IC_FORMA_RETORNO     CHAR(1)              NOT NULL,
   HH_LIMITE_RCBMO      TIME                 NOT NULL,
   DT_BASE              DATE                 NOT NULL
);

-- set table ownership
alter table D02TBP24_PRMOSSTMA owner to D02
;
ALTER TABLE D02TBP24_PRMOSSTMA
   ADD CONSTRAINT D02PKP24 PRIMARY KEY (NU_SGMNO_ORGM_S12);

CREATE UNIQUE INDEX D021IP24 ON D02TBP24_PRMOSSTMA (
NU_SGMNO_ORGM_S12
);

CREATE TABLE D02TBP25_PRMOUNDDE (
   NU_UNIDADE_U24       INT2                 NOT NULL
      CONSTRAINT CKC_NU_UNIDADE_U24_D02TBP25 CHECK (NU_UNIDADE_U24 BETWEEN 0001 AND 9999),
   NU_NATURAL_U24       INT4                 NOT NULL,
   IC_SITUACAO_UNDDE    CHAR(1)              NOT NULL,
   DT_CADASTRAMENTO     DATE                 NOT NULL,
   IC_MODO_ARQTO_FAA    CHAR(1)              NOT NULL,
   IC_EQPMO_FRMRO       INT2                 NOT NULL,
   QT_ESTQE_MNMO_AZUL   INT2                 NOT NULL,
   QT_ESTQE_MNMO_OCRE   INT2                 NOT NULL,
   QT_FORMULARIO_AZUL   INT2                 NOT NULL,
   QT_FORMULARIO_OCRE   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP25_PRMOUNDDE owner to D02
;
ALTER TABLE D02TBP25_PRMOUNDDE
   ADD CONSTRAINT D02PKP25 PRIMARY KEY (NU_UNIDADE_U24, NU_NATURAL_U24);

CREATE UNIQUE INDEX D021IP25 ON D02TBP25_PRMOUNDDE (
NU_UNIDADE_U24,
NU_NATURAL_U24
);

CREATE TABLE D02TBP26_CMPTOFNCE (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_FNCNE_ESPCL_P21   INT2                 NOT NULL,
   IC_LOCAL             INT2                 NOT NULL,
   IC_CMPTO_FNCNE       CHAR(1)              NOT NULL,
   NU_NIVEL_ALCDA_P54   INT2                 NULL
);

-- set table ownership
alter table D02TBP26_CMPTOFNCE owner to D02
;
ALTER TABLE D02TBP26_CMPTOFNCE
   ADD CONSTRAINT D02PKP26 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_FNCNE_ESPCL_P21, IC_LOCAL);

CREATE UNIQUE INDEX D021IP26 ON D02TBP26_CMPTOFNCE (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_FNCNE_ESPCL_P21,
IC_LOCAL
);

CREATE TABLE D02TBP27_ESPELHO (
   NU_UNIDADE_ESPHO     INT2                 NOT NULL,
   NU_PRODUTO_ESPHO     INT2                 NOT NULL,
   NU_CONTA_ESPELHO     INT4                 NOT NULL,
   NU_CONTA             DECIMAL(12)          NOT NULL,
   NU_PRODUTO           INT2                 NOT NULL,
   TS_CRIACAO_ESPELHO   DATE                 NOT NULL,
   NU_PARTICAO_CONTA    INT2                 NOT NULL,
   DT_MIGRACAO          DATE                 NOT NULL,
   DT_ABERTURA_ESPHO    DATE                 NULL
);

-- set table ownership
alter table D02TBP27_ESPELHO owner to D02
;
ALTER TABLE D02TBP27_ESPELHO
   ADD CONSTRAINT D02PKP27 PRIMARY KEY (NU_UNIDADE_ESPHO, NU_PRODUTO_ESPHO, NU_CONTA_ESPELHO);

CREATE UNIQUE INDEX D021IP27 ON D02TBP27_ESPELHO (
NU_UNIDADE_ESPHO,
NU_PRODUTO_ESPHO,
NU_CONTA_ESPELHO
);

CREATE  INDEX D022IP27 ON D02TBP27_ESPELHO (
NU_CONTA,
NU_PRODUTO
);

CREATE TABLE D02TBP28_HSTROCIF (
   TS_ALTERACAO_CIF     DATE                 NOT NULL,
   NU_ACAO_TRNSO        INT2                 NOT NULL,
   NU_MODO_TRNSO        INT2                 NOT NULL,
   NU_GRUPO_CMNDO       INT2                 NOT NULL,
   NU_SBGRO_CMNDO       INT2                 NOT NULL,
   NU_TIPO_CMNDO        INT2                 NOT NULL,
   NU_SBTPO_CMNDO       INT2                 NOT NULL,
   NU_NATURAL           INT4                 NOT NULL,
   NU_UNIDADE           INT2                 NOT NULL
      CONSTRAINT D022CP15 CHECK (NU_UNIDADE BETWEEN 0001 AND 9999),
   NO_CIF               VARCHAR(60)          NOT NULL,
   DT_CRIACAO_CIF       DATE                 NOT NULL,
   IC_SITUACAO_CIF      CHAR(1)              NOT NULL,
   DT_INICIO_VIGENCIA   DATE                 NOT NULL,
   DE_RESUMIDO_CIF      CHAR(10)             NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   NO_ABRVO_CIF         CHAR(25)             NOT NULL,
   VR_CUSTO_PRCSO       DECIMAL(5,2)         NULL,
   DT_FIM_VIGENCIA      DATE                 NULL,
   DE_MOTIVO_STCO_CIF   VARCHAR(40)          NULL,
   NU_PRIORIDADE        INT2                 NULL,
   IC_MVMNO_ESPTA       CHAR(1)              NOT NULL,
   IC_TIPO_OPERACAO     CHAR(1)              NOT NULL,
   NU_FNCNE_ESPCL_P21   INT2                 NULL,
   IC_PENDENCIA         CHAR(1)              NOT NULL DEFAULT 'N',
   IC_TIPO_EXTRACAO     CHAR(1)              NOT NULL DEFAULT 'N'
);

-- set table ownership
alter table D02TBP28_HSTROCIF owner to D02
;
ALTER TABLE D02TBP28_HSTROCIF
   ADD CONSTRAINT D02PKP28 PRIMARY KEY (TS_ALTERACAO_CIF);

CREATE UNIQUE INDEX D021IP28 ON D02TBP28_HSTROCIF (
TS_ALTERACAO_CIF
);

CREATE  INDEX D022IP28 ON D02TBP28_HSTROCIF (
NU_NATURAL,
NU_UNIDADE
);

CREATE TABLE D02TBP29_CIFCANAL (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_CANAL_CMRCO_P31   INT2                 NOT NULL,
   IC_STCO_CIF_CANAL    CHAR(1)              NOT NULL,
   DE_MTVO_STCO_CANAL   CHAR(40)             NULL
);

-- set table ownership
alter table D02TBP29_CIFCANAL owner to D02
;
ALTER TABLE D02TBP29_CIFCANAL
   ADD CONSTRAINT D02PKP29 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_CANAL_CMRCO_P31);

CREATE UNIQUE INDEX D021IP29 ON D02TBP29_CIFCANAL (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_CANAL_CMRCO_P31
);

CREATE TABLE D02TBP30_CIFSSTMA (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SGMNO_ORGM_P24    INT2                 NOT NULL,
   IC_STCO_CIF_SSTMA    CHAR(1)              NOT NULL,
   DE_MTVO_STCO_SSTMA   CHAR(40)             NULL
);

-- set table ownership
alter table D02TBP30_CIFSSTMA owner to D02
;
ALTER TABLE D02TBP30_CIFSSTMA
   ADD CONSTRAINT D02PKP30 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_SGMNO_ORGM_P24);

CREATE UNIQUE INDEX D021IP30 ON D02TBP30_CIFSSTMA (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_SGMNO_ORGM_P24
);

CREATE TABLE D02TBP31_CANAL (
   NU_CANAL_CMRCO_O15   INT2                 NOT NULL,
   IC_SITUACAO_CANAL    CHAR(1)              NOT NULL
);

-- set table ownership
alter table D02TBP31_CANAL owner to D02
;
ALTER TABLE D02TBP31_CANAL
   ADD CONSTRAINT D02PKP31 PRIMARY KEY (NU_CANAL_CMRCO_O15);

CREATE UNIQUE INDEX D021IP31 ON D02TBP31_CANAL (
NU_CANAL_CMRCO_O15
);

CREATE TABLE D02TBP32_CIFAGRDO (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_ACAO_AGRDO_P15    INT2                 NOT NULL,
   NU_MODO_AGRDO_P15    INT2                 NOT NULL,
   NU_GRUPO_AGRDO_P15   INT2                 NOT NULL,
   NU_SBGRO_AGRDO_P15   INT2                 NOT NULL,
   NU_TIPO_AGRDO_P15    INT2                 NOT NULL,
   NU_SBTPO_AGRDO_P15   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP32_CIFAGRDO owner to D02
;
ALTER TABLE D02TBP32_CIFAGRDO
   ADD CONSTRAINT D02PKP32 PRIMARY KEY (NU_ACAO_AGRDO_P15, NU_MODO_AGRDO_P15, NU_GRUPO_AGRDO_P15, NU_SBGRO_AGRDO_P15, NU_TIPO_AGRDO_P15, NU_SBTPO_AGRDO_P15, NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15);

CREATE UNIQUE INDEX D021IP32 ON D02TBP32_CIFAGRDO (
NU_ACAO_AGRDO_P15,
NU_MODO_AGRDO_P15,
NU_GRUPO_AGRDO_P15,
NU_SBGRO_AGRDO_P15,
NU_TIPO_AGRDO_P15,
NU_SBTPO_AGRDO_P15,
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15
);

CREATE TABLE D02TBP33_DSCODTLHA (
   NU_DSCRO_DTLHA       INT4                 NOT NULL,
   NO_DSCRO_DTLHA       VARCHAR(60)          NOT NULL,
   NO_ABRDO_DSCRO       CHAR(25)             NOT NULL,
   NO_DSCRO_RESUMIDA    CHAR(10)             NULL
);

-- set table ownership
alter table D02TBP33_DSCODTLHA owner to D02
;
ALTER TABLE D02TBP33_DSCODTLHA
   ADD CONSTRAINT D02PKP33 PRIMARY KEY (NU_DSCRO_DTLHA);

CREATE UNIQUE INDEX D021IP33 ON D02TBP33_DSCODTLHA (
NU_DSCRO_DTLHA
);

CREATE TABLE D02TBP34_HSOCIFPRE (
   TS_ALTERACAO_CIF     DATE                 NOT NULL,
   NU_ACAO_TRNSO_P16    INT2                 NOT NULL,
   NU_MODO_TRNSO_P16    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P16   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P16   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P16    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P16   INT2                 NOT NULL,
   NU_PRODUTO_P16       INT2                 NOT NULL,
   NU_PRPRE_PRDTO_P16   INT2                 NOT NULL,
   IC_STCO_CIF_PRPRE    CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   DE_MOTIVO_SITUACAO   CHAR(60)             NULL
);

-- set table ownership
alter table D02TBP34_HSOCIFPRE owner to D02
;
ALTER TABLE D02TBP34_HSOCIFPRE
   ADD CONSTRAINT D02PKP34 PRIMARY KEY (TS_ALTERACAO_CIF);

CREATE UNIQUE INDEX D021IP34 ON D02TBP34_HSOCIFPRE (
TS_ALTERACAO_CIF
);

CREATE TABLE D02TBP37_STCOCTRTO (
   NU_SITUACAO_CTRTO    INT2                 NOT NULL,
   NO_SITUACAO_CTRTO    CHAR(100)            NOT NULL
);

-- set table ownership
alter table D02TBP37_STCOCTRTO owner to D02
;
ALTER TABLE D02TBP37_STCOCTRTO
   ADD CONSTRAINT D02PKP37 PRIMARY KEY (NU_SITUACAO_CTRTO);

CREATE UNIQUE INDEX D021IP37 ON D02TBP37_STCOCTRTO (
NU_SITUACAO_CTRTO
);

CREATE TABLE D02TBP41_CMPTOSTCO (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SITUACAO_P37      INT2                 NOT NULL,
   IC_CMPTO_SITUACAO    CHAR(1)              NOT NULL
);

-- set table ownership
alter table D02TBP41_CMPTOSTCO owner to D02
;
ALTER TABLE D02TBP41_CMPTOSTCO
   ADD CONSTRAINT D02PKP41 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_SITUACAO_P37);

CREATE UNIQUE INDEX D021IP41 ON D02TBP41_CMPTOSTCO (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_SITUACAO_P37
);

CREATE TABLE D02TBP42_CIFTDCL (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_TD_P43            INT2                 NOT NULL,
   NU_CL_P43            INT2                 NOT NULL,
   NU_TIPO_TDCL_P43     INT2                 NOT NULL,
   NU_DIA_TDCL_P43      INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP42_CIFTDCL owner to D02
;
ALTER TABLE D02TBP42_CIFTDCL
   ADD CONSTRAINT D02PKP42 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_TD_P43, NU_CL_P43, NU_TIPO_TDCL_P43, NU_DIA_TDCL_P43);

CREATE UNIQUE INDEX D021IP42 ON D02TBP42_CIFTDCL (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_TD_P43,
NU_CL_P43,
NU_TIPO_TDCL_P43,
NU_DIA_TDCL_P43
);

CREATE  INDEX D022IP42 ON D02TBP42_CIFTDCL (
NU_TD_P43,
NU_CL_P43,
NU_TIPO_TDCL_P43,
NU_DIA_TDCL_P43
);

CREATE TABLE D02TBP43_TDCL (
   NU_TD                INT2                 NOT NULL,
   NU_CL                INT2                 NOT NULL,
   NU_TIPO_TDCL         INT2                 NOT NULL,
   NU_DIA_TDCL          INT2                 NOT NULL,
   NO_TDCL              CHAR(60)             NOT NULL,
   NU_LOTE_TDCL         INT2                 NOT NULL,
   NU_CF_TDCL           INT2                 NOT NULL,
   NU_SCF_TDCL          INT2                 NOT NULL,
   IC_SITUACAO_TDCL     CHAR(1)              NOT NULL
);

-- set table ownership
alter table D02TBP43_TDCL owner to D02
;
ALTER TABLE D02TBP43_TDCL
   ADD CONSTRAINT D02PKP43 PRIMARY KEY (NU_TD, NU_CL, NU_TIPO_TDCL, NU_DIA_TDCL);

CREATE UNIQUE INDEX D021IP43 ON D02TBP43_TDCL (
NU_TD,
NU_CL,
NU_TIPO_TDCL,
NU_DIA_TDCL
);

CREATE TABLE D02TBP44_ARQVORCBO (
   TS_RCBMO_ARQO_ORGM   DATE                 NOT NULL,
   NU_SEGMENTO_S12      INT2                 NOT NULL,
   CO_TPO_MSG_SSA_P23   CHAR(2)              NULL,
   NU_MNSGM_SSTMA_P23   INT2                 NULL,
   QT_RGSO_RCBMO_ORGM   INT4                 NOT NULL,
   NU_REMESSA           INT4                 NOT NULL,
   IC_STCO_ARQUIVO      INT2                 NOT NULL,
   VR_TOTAL_ARQUIVO     DECIMAL(15,2)        NULL,
   DT_MOVIMENTO         DATE                 NULL
);

-- set table ownership
alter table D02TBP44_ARQVORCBO owner to D02
;
ALTER TABLE D02TBP44_ARQVORCBO
   ADD CONSTRAINT D02PKP44 PRIMARY KEY (TS_RCBMO_ARQO_ORGM, NU_SEGMENTO_S12);

CREATE UNIQUE INDEX D021IP44 ON D02TBP44_ARQVORCBO (
TS_RCBMO_ARQO_ORGM,
NU_SEGMENTO_S12
);

CREATE TABLE D02TBP45_TABELA (
   NO_TABELA            CHAR(18)             NOT NULL
);

-- set table ownership
alter table D02TBP45_TABELA owner to D02
;
ALTER TABLE D02TBP45_TABELA
   ADD CONSTRAINT D02PKP45 PRIMARY KEY (NO_TABELA);

CREATE UNIQUE INDEX D021IP45 ON D02TBP45_TABELA (
NO_TABELA
);

CREATE TABLE D02TBP46_COLUNA (
   NO_COLUNA            CHAR(18)             NOT NULL,
   NO_TABELA_P45        CHAR(18)             NOT NULL
);

-- set table ownership
alter table D02TBP46_COLUNA owner to D02
;
ALTER TABLE D02TBP46_COLUNA
   ADD CONSTRAINT D02PKP46 PRIMARY KEY (NO_COLUNA, NO_TABELA_P45);

CREATE UNIQUE INDEX D021IP46 ON D02TBP46_COLUNA (
NO_COLUNA,
NO_TABELA_P45
);

CREATE TABLE D02TBP47_CONTEUDO (
   NU_HISTORICO         INT4                 NOT NULL,
   NO_TABELA_P46        CHAR(18)             NOT NULL,
   NO_COLUNA_P46        CHAR(18)             NOT NULL,
   IC_TIPO_OPERACAO     CHAR(1)              NOT NULL,
   CO_TERMINAL          CHAR(15)             NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   DT_ATUALIZACAO       DATE                 NOT NULL,
   HH_ATUALIZACAO       TIME                 NOT NULL,
   DE_CONTEUDO_ATUAL    VARCHAR(400)         NOT NULL,
   DE_CNDO_ANTERIOR     VARCHAR(400)         NULL
);

-- set table ownership
alter table D02TBP47_CONTEUDO owner to D02
;
ALTER TABLE D02TBP47_CONTEUDO
   ADD CONSTRAINT D02PKP47 PRIMARY KEY (NU_HISTORICO, NO_TABELA_P46, NO_COLUNA_P46);

CREATE UNIQUE INDEX D021IP47 ON D02TBP47_CONTEUDO (
NU_HISTORICO,
NO_TABELA_P46,
NO_COLUNA_P46
);

CREATE TABLE D02TBP48_TIPOSALDO (
   NU_TIPO_SALDO        INT2                 NOT NULL,
   NO_TIPO_SALDO        CHAR(60)             NOT NULL
);

-- set table ownership
alter table D02TBP48_TIPOSALDO owner to D02
;
ALTER TABLE D02TBP48_TIPOSALDO
   ADD CONSTRAINT D02PKP48 PRIMARY KEY (NU_TIPO_SALDO);

CREATE UNIQUE INDEX D021IP48 ON D02TBP48_TIPOSALDO (
NU_TIPO_SALDO
);

CREATE TABLE D02TBP49_CIFTPOSDO (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_SALDO_P48    INT2                 NOT NULL,
   IC_SINAL             INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP49_CIFTPOSDO owner to D02
;
ALTER TABLE D02TBP49_CIFTPOSDO
   ADD CONSTRAINT D02PKP49 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_TIPO_SALDO_P48);

CREATE UNIQUE INDEX D021IP49 ON D02TBP49_CIFTPOSDO (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_TIPO_SALDO_P48
);

CREATE TABLE D02TBP50_PRMOCNTLE (
   NU_PARAMETRO_CNTLE   INT2                 NOT NULL,
   DE_PARAMETRO_CNTLE   CHAR(150)            NULL
);

-- set table ownership
alter table D02TBP50_PRMOCNTLE owner to D02
;
ALTER TABLE D02TBP50_PRMOCNTLE
   ADD CONSTRAINT D02PKP50 PRIMARY KEY (NU_PARAMETRO_CNTLE);

CREATE UNIQUE INDEX D021IP50 ON D02TBP50_PRMOCNTLE (
NU_PARAMETRO_CNTLE
);

CREATE TABLE D02TBP51_ITEMPRMTO (
   NU_PRMTO_CNTLE_P50   INT2                 NOT NULL,
   NU_ITEM_PARAMETRO    INT2                 NOT NULL,
   DE_CNDO_ITEM_PRMTO   CHAR(10)             NOT NULL,
   DT_INICIO_PRMTO      DATE                 NOT NULL,
   DT_FIM_PARAMETRO     DATE                 NULL,
   DE_ITEM_PARAMETRO    VARCHAR(300)         NOT NULL
);

-- set table ownership
alter table D02TBP51_ITEMPRMTO owner to D02
;
ALTER TABLE D02TBP51_ITEMPRMTO
   ADD CONSTRAINT D02PKP51 PRIMARY KEY (NU_PRMTO_CNTLE_P50, NU_ITEM_PARAMETRO);

CREATE UNIQUE INDEX D021IP51 ON D02TBP51_ITEMPRMTO (
NU_PRMTO_CNTLE_P50,
NU_ITEM_PARAMETRO
);

CREATE TABLE D02TBP52_CTLEOCRNA (
   DT_OCORRENCIA        DATE                 NOT NULL,
   HH_OCORRENCIA        TIME                 NOT NULL,
   QT_SEGUNDO_OCRNA     INT4                 NOT NULL,
   CO_PROGRAMA          CHAR(8)              NOT NULL,
   NU_CONTROLE          INT4                 NOT NULL,
   QT_RNCDA_OCRNA       INT2                 NOT NULL,
   NU_RETORNO_PRGRA     INT4                 NOT NULL,
   IC_TIPO_OCORRENCIA   INT2                 NOT NULL,
   CO_TPO_MNSGM_SSTMA   CHAR(2)              NULL,
   NU_MNSGM_SISTEMA     INT2                 NULL,
   NU_IDNTR_UNICO       DECIMAL(20)          NULL,
   CO_SUBROTINA         CHAR(8)              NULL,
   CO_RTRNO_SUBROTINA   CHAR(20)             NULL,
   NU_NSU_ORIGEM        DECIMAL(20)          NULL,
   NU_RETORNO_DB2       INT2                 NULL,
   NU_RETORNO_CICS      INT2                 NULL,
   NU_ACAO_TRANSACAO    INT2                 NULL,
   NU_MODO_TRANSACAO    INT2                 NULL,
   NU_GRUPO_COMANDO     INT2                 NULL,
   NU_SUBGRUPO_CMNDO    INT2                 NULL,
   NU_TIPO_COMANDO      INT2                 NULL,
   NU_SUBTIPO_COMANDO   INT2                 NULL,
   CO_IDNFO_CICS        CHAR(8)              NULL,
   CO_TRANSACAO         CHAR(4)              NULL,
   NU_CONTA             DECIMAL(12)          NULL,
   NU_DV_CONTA          INT2                 NULL,
   NU_PRODUTO           INT2                 NULL,
   NU_PRPRE_PRODUTO     INT2                 NULL,
   NU_UNIDADE           INT2                 NULL,
   NU_NATURAL           INT4                 NULL,
   NU_REDE_TRNMA        DECIMAL(11)          NULL,
   NU_SEGMENTO          INT2                 NULL,
   NU_CANAL_CMRZO       INT2                 NULL,
   NU_NSU_SOLUCAO       INT4                 NULL,
   NU_NSU_INTMO         DECIMAL(20)          NULL,
   NU_NSU_DESTINO       DECIMAL(20)          NULL,
   NU_MENSAGEM_PACOTE   INT2                 NULL,
   NO_TABELA            CHAR(8)              NULL,
   CO_ARQUIVO           CHAR(8)              NULL,
   VR_TRANSACAO         DECIMAL(15,2)        NULL,
   DE_MNSGM_OCRNA       VARCHAR(200)         NULL
);

-- set table ownership
alter table D02TBP52_CTLEOCRNA owner to D02
;
ALTER TABLE D02TBP52_CTLEOCRNA
   ADD CONSTRAINT D02PKP52 PRIMARY KEY (DT_OCORRENCIA, HH_OCORRENCIA, QT_SEGUNDO_OCRNA, CO_PROGRAMA, NU_CONTROLE);

CREATE UNIQUE INDEX D021IP52 ON D02TBP52_CTLEOCRNA (
DT_OCORRENCIA,
HH_OCORRENCIA,
QT_SEGUNDO_OCRNA,
CO_PROGRAMA,
NU_CONTROLE
);

CREATE TABLE D02TBP53_PRDTODSTO (
   NU_PRODUTO_O10       INT2                 NOT NULL,
   IC_STCO_PRDTO_DSTO   CHAR(1)              NOT NULL,
   DT_MIGRACAO          DATE                 NULL
);

-- set table ownership
alter table D02TBP53_PRDTODSTO owner to D02
;
ALTER TABLE D02TBP53_PRDTODSTO
   ADD CONSTRAINT D02PKP53 PRIMARY KEY (NU_PRODUTO_O10);

CREATE UNIQUE INDEX D021IP53 ON D02TBP53_PRDTODSTO (
NU_PRODUTO_O10
);

CREATE TABLE D02TBP54_NVLALCDA (
   NU_NIVEL_ALCADA      INT2                 NOT NULL,
   NO_NIVEL_ALCADA      CHAR(60)             NOT NULL
);

-- set table ownership
alter table D02TBP54_NVLALCDA owner to D02
;
ALTER TABLE D02TBP54_NVLALCDA
   ADD CONSTRAINT D02PKP54 PRIMARY KEY (NU_NIVEL_ALCADA);

CREATE UNIQUE INDEX D021IP54 ON D02TBP54_NVLALCDA (
NU_NIVEL_ALCADA
);

CREATE TABLE D02TBP55_PRDELNCMO (
   NU_PRIORIDADE        INT2                 NOT NULL,
   DE_PRIORIDADE        CHAR(120)            NOT NULL
);

-- set table ownership
alter table D02TBP55_PRDELNCMO owner to D02
;
ALTER TABLE D02TBP55_PRDELNCMO
   ADD CONSTRAINT D02PKP55 PRIMARY KEY (NU_PRIORIDADE);

CREATE UNIQUE INDEX D021IP55 ON D02TBP55_PRDELNCMO (
NU_PRIORIDADE
);

CREATE TABLE D02TBP56_CIFFNCNE (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_FNCNE_ESPCL_P21   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP56_CIFFNCNE owner to D02
;
ALTER TABLE D02TBP56_CIFFNCNE
   ADD CONSTRAINT D02PKP56 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15);

CREATE UNIQUE INDEX D021IP56 ON D02TBP56_CIFFNCNE (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15
);

CREATE TABLE D02TBP57_MTVOCTRTO (
   NU_MOTIVO_CTRTO      INT2                 NOT NULL,
   NO_MOTIVO_CTRTO      CHAR(100)            NOT NULL
);

-- set table ownership
alter table D02TBP57_MTVOCTRTO owner to D02
;
ALTER TABLE D02TBP57_MTVOCTRTO
   ADD CONSTRAINT D02PKP57 PRIMARY KEY (NU_MOTIVO_CTRTO);

CREATE UNIQUE INDEX D021IP57 ON D02TBP57_MTVOCTRTO (
NU_MOTIVO_CTRTO
);

CREATE TABLE D02TBP58_STCOMTVO (
   NU_SITUACAO_P37      INT2                 NOT NULL,
   NU_MOTIVO_P57        INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP58_STCOMTVO owner to D02
;
ALTER TABLE D02TBP58_STCOMTVO
   ADD CONSTRAINT D02PKP58 PRIMARY KEY (NU_SITUACAO_P37, NU_MOTIVO_P57);

CREATE UNIQUE INDEX D021IP58 ON D02TBP58_STCOMTVO (
NU_SITUACAO_P37,
NU_MOTIVO_P57
);

CREATE TABLE D02TBP59_CRGRA (
   NU_COREOGRAFIA       INT4                 NOT NULL,
   NO_COREOGRAFIA       VARCHAR(100)         NOT NULL
);

-- set table ownership
alter table D02TBP59_CRGRA owner to D02
;
ALTER TABLE D02TBP59_CRGRA
   ADD CONSTRAINT D02PKP59 PRIMARY KEY (NU_COREOGRAFIA);

CREATE UNIQUE INDEX D021IP59 ON D02TBP59_CRGRA (
NU_COREOGRAFIA
);

CREATE TABLE D02TBP60_PASSO (
   CO_PASSO             CHAR(8)              NOT NULL,
   NO_PASSO             VARCHAR(100)         NOT NULL
);

-- set table ownership
alter table D02TBP60_PASSO owner to D02
;
ALTER TABLE D02TBP60_PASSO
   ADD CONSTRAINT D02PKP60 PRIMARY KEY (CO_PASSO);

CREATE UNIQUE INDEX D021IP60 ON D02TBP60_PASSO (
CO_PASSO
);

CREATE TABLE D02TBP61_CRGRAPSSO (
   NU_COREOGRAFIA_P59   INT4                 NOT NULL,
   CO_PASSO_P60         CHAR(8)              NOT NULL
);

-- set table ownership
alter table D02TBP61_CRGRAPSSO owner to D02
;
ALTER TABLE D02TBP61_CRGRAPSSO
   ADD CONSTRAINT D02PKP61 PRIMARY KEY (NU_COREOGRAFIA_P59, CO_PASSO_P60);

CREATE UNIQUE INDEX D021IP61 ON D02TBP61_CRGRAPSSO (
NU_COREOGRAFIA_P59,
CO_PASSO_P60
);

CREATE TABLE D02TBP62_FLXOCRGRA (
   NU_COREOGRAFIA_P61   INT4                 NOT NULL,
   CO_PASSO_P61         CHAR(8)              NOT NULL,
   NU_RETORNO           INT2                 NOT NULL,
   CO_PRXMO_PASSO_P61   CHAR(8)              NOT NULL
);

-- set table ownership
alter table D02TBP62_FLXOCRGRA owner to D02
;
ALTER TABLE D02TBP62_FLXOCRGRA
   ADD CONSTRAINT D02PKP62 PRIMARY KEY (NU_COREOGRAFIA_P61, CO_PASSO_P61, NU_RETORNO);

CREATE UNIQUE INDEX D021IP62 ON D02TBP62_FLXOCRGRA (
NU_COREOGRAFIA_P61,
CO_PASSO_P61,
NU_RETORNO
);

CREATE TABLE D02TBP63_CIFCRGRA (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SGMNO_ORGM_P24    INT2                 NOT NULL,
   NU_PACOTE            INT2                 NOT NULL,
   NU_COREOGRAFIA_P59   INT4                 NOT NULL
);

-- set table ownership
alter table D02TBP63_CIFCRGRA owner to D02
;
ALTER TABLE D02TBP63_CIFCRGRA
   ADD CONSTRAINT D02PKP63 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_SGMNO_ORGM_P24, NU_PACOTE);

CREATE UNIQUE INDEX D021IP63 ON D02TBP63_CIFCRGRA (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_SGMNO_ORGM_P24,
NU_PACOTE
);

CREATE TABLE D02TBP64_CMPTOSTCO (
   NU_ACAO_TRNSO_P15    INT2                 NOT NULL,
   NU_MODO_TRNSO_P15    INT2                 NOT NULL,
   NU_GRUPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SBGRO_CMNDO_P15   INT2                 NOT NULL,
   NU_TIPO_CMNDO_P15    INT2                 NOT NULL,
   NU_SBTPO_CMNDO_P15   INT2                 NOT NULL,
   NU_SITUACAO_P58      INT2                 NOT NULL,
   NU_MOTIVO_P58        INT2                 NOT NULL,
   IC_CMPTO_SITUACAO    CHAR(1)              NOT NULL
);

-- set table ownership
alter table D02TBP64_CMPTOSTCO owner to D02
;
ALTER TABLE D02TBP64_CMPTOSTCO
   ADD CONSTRAINT D02PKP64 PRIMARY KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_SITUACAO_P58, NU_MOTIVO_P58);

CREATE UNIQUE INDEX D021IP64 ON D02TBP64_CMPTOSTCO (
NU_ACAO_TRNSO_P15,
NU_MODO_TRNSO_P15,
NU_GRUPO_CMNDO_P15,
NU_SBGRO_CMNDO_P15,
NU_TIPO_CMNDO_P15,
NU_SBTPO_CMNDO_P15,
NU_SITUACAO_P58,
NU_MOTIVO_P58
);

CREATE TABLE D02TBP65_ARQVORCBO (
   NU_SGMNO_ORGM_P24    INT2                 NOT NULL,
   NU_REMESSA           INT4                 NOT NULL,
   DT_MOVIMENTO         DATE                 NOT NULL,
   DT_GERACAO           DATE                 NOT NULL,
   HH_GERACAO           TIME                 NOT NULL,
   TS_RECEBIMENTO       DATE                 NOT NULL,
   QT_REGISTRO          INT4                 NOT NULL,
   VR_TOTAL_ARQUIVO     DECIMAL(15,2)        NOT NULL,
   IC_SITUACAO          INT2                 NOT NULL,
   CO_TPO_MSG_SSA_P23   CHAR(2)              NOT NULL,
   NU_MNSGM_SSTMA_P23   INT2                 NOT NULL
);

-- set table ownership
alter table D02TBP65_ARQVORCBO owner to D02
;
ALTER TABLE D02TBP65_ARQVORCBO
   ADD CONSTRAINT D02PKP65 PRIMARY KEY (NU_SGMNO_ORGM_P24, NU_REMESSA);

CREATE UNIQUE INDEX D021IP65 ON D02TBP65_ARQVORCBO (
NU_SGMNO_ORGM_P24,
NU_REMESSA
);

CREATE TABLE D02TBP66_CTLEOCRNA (
   DT_OCORRENCIA        DATE                 NOT NULL,
   NU_OCORRENCIA        INT4                 NOT NULL,
   CO_PROGRAMA          CHAR(8)              NOT NULL,
   NU_CONTROLE          INT4                 NOT NULL,
   NU_RETORNO_PRGRA     INT4                 NOT NULL,
   CO_TPO_MNSGM_SSTMA   CHAR(2)              NOT NULL,
   NU_MNSGM_SISTEMA     INT2                 NOT NULL,
   TS_OCORRENCIA        DATE                 NOT NULL,
   NU_UNIDADE           INT2                 NULL,
   NU_NATURAL           INT4                 NULL,
   NU_CONTA             DECIMAL(12)          NULL,
   NU_PRODUTO           INT2                 NULL,
   NU_PRPRE_PRODUTO     INT2                 NULL,
   CO_SUBROTINA         CHAR(8)              NULL,
   CO_RTRNO_SUBROTINA   CHAR(20)             NULL,
   NO_TABELA            CHAR(8)              NULL,
   NU_RETORNO_DB2       INT2                 NULL,
   CO_IDNFO_CICS        CHAR(8)              NULL,
   CO_TRANSACAO         CHAR(4)              NULL,
   NU_RETORNO_CICS      INT2                 NULL,
   NU_ACAO_TRANSACAO    INT2                 NULL,
   NU_MODO_TRANSACAO    INT2                 NULL,
   NU_GRUPO_COMANDO     INT2                 NULL,
   NU_SUBGRUPO_CMNDO    INT2                 NULL,
   NU_TIPO_COMANDO      INT2                 NULL,
   NU_SUBTIPO_COMANDO   INT2                 NULL,
   NU_SEGMENTO_ORIGEM   INT2                 NULL,
   CO_OPERADOR          CHAR(8)              NULL,
   DE_MNSGM_OCRNA       VARCHAR(1000)        NULL
);

-- set table ownership
alter table D02TBP66_CTLEOCRNA owner to D02
;
ALTER TABLE D02TBP66_CTLEOCRNA
   ADD CONSTRAINT D02PKP66 PRIMARY KEY (DT_OCORRENCIA, NU_OCORRENCIA);

CREATE UNIQUE INDEX D021IP66 ON D02TBP66_CTLEOCRNA (
DT_OCORRENCIA,
NU_OCORRENCIA
);

CREATE TABLE D02TBP67_HSTOCRGRA (
   TS_MANUTENCAO        DATE                 NOT NULL,
   IC_TIPO_MANUTENCAO   CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   NU_COREOGRAFIA       INT4                 NOT NULL,
   NO_COREOGRAFIA       CHAR(100)            NOT NULL
);

-- set table ownership
alter table D02TBP67_HSTOCRGRA owner to D02
;
ALTER TABLE D02TBP67_HSTOCRGRA
   ADD CONSTRAINT D02PKP67 PRIMARY KEY (TS_MANUTENCAO, IC_TIPO_MANUTENCAO);

CREATE UNIQUE INDEX D021IP67 ON D02TBP67_HSTOCRGRA (
TS_MANUTENCAO,
IC_TIPO_MANUTENCAO
);

CREATE TABLE D02TBP68_HSTROPSSO (
   TS_MANUTENCAO        DATE                 NOT NULL,
   IC_TIPO_MANUTENCAO   CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   CO_PASSO             CHAR(8)              NOT NULL,
   NO_PASSO             CHAR(100)            NOT NULL
);

-- set table ownership
alter table D02TBP68_HSTROPSSO owner to D02
;
ALTER TABLE D02TBP68_HSTROPSSO
   ADD CONSTRAINT D02PKP68 PRIMARY KEY (TS_MANUTENCAO, IC_TIPO_MANUTENCAO);

CREATE UNIQUE INDEX D021IP68 ON D02TBP68_HSTROPSSO (
TS_MANUTENCAO,
IC_TIPO_MANUTENCAO
);

CREATE TABLE D02TBP69_HTOCRGPSO (
   TS_MANUTENCAO        DATE                 NOT NULL,
   IC_TIPO_MANUTENCAO   CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   NU_COREOGRAFIA       INT4                 NOT NULL,
   CO_PASSO             CHAR(8)              NOT NULL
);

-- set table ownership
alter table D02TBP69_HTOCRGPSO owner to D02
;
ALTER TABLE D02TBP69_HTOCRGPSO
   ADD CONSTRAINT D02PKP69 PRIMARY KEY (TS_MANUTENCAO, IC_TIPO_MANUTENCAO);

CREATE UNIQUE INDEX D021IP69 ON D02TBP69_HTOCRGPSO (
TS_MANUTENCAO,
IC_TIPO_MANUTENCAO
);

CREATE TABLE D02TBP70_HTOFLXCGA (
   TS_MANUTENCAO        DATE                 NOT NULL,
   IC_TIPO_MANUTENCAO   CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   NU_COREOGRAFIA       INT4                 NOT NULL,
   CO_PASSO             CHAR(8)              NOT NULL,
   NU_RETORNO           INT2                 NOT NULL,
   CO_PRXMO_PASSO       CHAR(8)              NOT NULL
);

-- set table ownership
alter table D02TBP70_HTOFLXCGA owner to D02
;
ALTER TABLE D02TBP70_HTOFLXCGA
   ADD CONSTRAINT D02PKP70 PRIMARY KEY (TS_MANUTENCAO, IC_TIPO_MANUTENCAO);

CREATE UNIQUE INDEX D021IP70 ON D02TBP70_HTOFLXCGA (
TS_MANUTENCAO,
IC_TIPO_MANUTENCAO
);

CREATE TABLE D02TBP71_HTOCIFCGA (
   TS_MANUTENCAO        DATE                 NOT NULL,
   IC_TIPO_MANUTENCAO   CHAR(1)              NOT NULL,
   CO_USUARIO           CHAR(8)              NOT NULL,
   NU_ACAO_TRNSO        INT2                 NOT NULL,
   NU_MODO_TRNSO        INT2                 NOT NULL,
   NU_GRUPO_COMANDO     INT2                 NOT NULL,
   NU_SBGRO_COMANDO     INT2                 NOT NULL,
   NU_TIPO_COMANDO      INT2                 NOT NULL,
   NU_SBTPO_COMANDO     INT2                 NOT NULL,
   NU_SGMNO_ORIGEM      INT2                 NOT NULL,
   NU_PACOTE            INT2                 NOT NULL,
   NU_COREOGRAFIA       INT4                 NOT NULL
);

-- set table ownership
alter table D02TBP71_HTOCIFCGA owner to D02
;
ALTER TABLE D02TBP71_HTOCIFCGA
   ADD CONSTRAINT D02PKP71 PRIMARY KEY (TS_MANUTENCAO, IC_TIPO_MANUTENCAO);

CREATE UNIQUE INDEX D021IP71 ON D02TBP71_HTOCIFCGA (
TS_MANUTENCAO,
IC_TIPO_MANUTENCAO
);

ALTER TABLE D02TBP01_PRMOPRPRE
   ADD CONSTRAINT D021FP01 FOREIGN KEY (NU_PRODUTO_P20, NU_PRPRE_PRDTO_P20)
      REFERENCES D02TBP20_PRPREDSTO (NU_PRODUTO_O28, NU_PRPRE_PRDTO_O28)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP01_PRMOPRPRE
   ADD CONSTRAINT D022FP01 FOREIGN KEY (NU_PRODUTO_P20, NU_TIPO_PRMTO_P03)
      REFERENCES D02TBP03_PRMOPRDTO (NU_PRODUTO_P53, NU_TIPO_PRMTO_P02)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP03_PRMOPRDTO
   ADD CONSTRAINT D021FP03 FOREIGN KEY (NU_PRODUTO_P53)
      REFERENCES D02TBP53_PRDTODSTO (NU_PRODUTO_O10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP03_PRMOPRDTO
   ADD CONSTRAINT D022FP03 FOREIGN KEY (NU_TIPO_PRMTO_P02)
      REFERENCES D02TBP02_TIPOPRMTO (NU_TIPO_PARAMETRO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP06_GRSBCMNDO
   ADD CONSTRAINT D021FP06 FOREIGN KEY (NU_SBGRO_CMNDO_P05)
      REFERENCES D02TBP05_SBGOCMNDO (NU_SUBGRUPO_CMNDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP06_GRSBCMNDO
   ADD CONSTRAINT D022FP06 FOREIGN KEY (NU_GRUPO_CMNDO_P04)
      REFERENCES D02TBP04_GRPOCMNDO (NU_GRUPO_COMANDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP09_TPSBCMNDO
   ADD CONSTRAINT D021FP09 FOREIGN KEY (NU_SBTPO_CMNDO_P08)
      REFERENCES D02TBP08_SBTOCMNDO (NU_SUBTIPO_COMANDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP09_TPSBCMNDO
   ADD CONSTRAINT D022FP09 FOREIGN KEY (NU_TIPO_CMNDO_P07)
      REFERENCES D02TBP07_TIPOCMNDO (NU_TIPO_COMANDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP10_COMANDO
   ADD CONSTRAINT D021FP10 FOREIGN KEY (NU_GRUPO_CMNDO_P06, NU_SBGRO_CMNDO_P06)
      REFERENCES D02TBP06_GRSBCMNDO (NU_GRUPO_CMNDO_P04, NU_SBGRO_CMNDO_P05)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP10_COMANDO
   ADD CONSTRAINT D022FP10 FOREIGN KEY (NU_TIPO_CMNDO_P09, NU_SBTPO_CMNDO_P09)
      REFERENCES D02TBP09_TPSBCMNDO (NU_TIPO_CMNDO_P07, NU_SBTPO_CMNDO_P08)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP13_ACMDTRNSO
   ADD CONSTRAINT D021FP13 FOREIGN KEY (NU_MODO_TRNSO_P12)
      REFERENCES D02TBP12_MODOTRNSO (NU_MODO_TRANSACAO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP13_ACMDTRNSO
   ADD CONSTRAINT D022FP13 FOREIGN KEY (NU_ACAO_TRNSO_P11)
      REFERENCES D02TBP11_ACAOTRNSO (NU_ACAO_TRANSACAO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP14_ACMDGRPO
   ADD CONSTRAINT D021FP14 FOREIGN KEY (NU_ACAO_TRNSO_P13, NU_MODO_TRNSO_P13)
      REFERENCES D02TBP13_ACMDTRNSO (NU_ACAO_TRNSO_P11, NU_MODO_TRNSO_P12)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP14_ACMDGRPO
   ADD CONSTRAINT D022FP14 FOREIGN KEY (NU_GRUPO_CMNDO_P04)
      REFERENCES D02TBP04_GRPOCMNDO (NU_GRUPO_COMANDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP15_CIF
   ADD CONSTRAINT D021FP15 FOREIGN KEY (NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      REFERENCES D02TBP10_COMANDO (NU_GRUPO_CMNDO_P06, NU_SBGRO_CMNDO_P06, NU_TIPO_CMNDO_P09, NU_SBTPO_CMNDO_P09)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP15_CIF
   ADD CONSTRAINT D022FP15 FOREIGN KEY (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10)
      REFERENCES D02TBP14_ACMDGRPO (NU_ACAO_TRNSO_P13, NU_MODO_TRNSO_P13, NU_GRUPO_CMNDO_P04)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP15_CIF
   ADD CONSTRAINT D024FP15 FOREIGN KEY (NU_PRIORIDADE_P55)
      REFERENCES D02TBP55_PRDELNCMO (NU_PRIORIDADE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP15_CIF
   ADD CONSTRAINT D025FP15 FOREIGN KEY (NU_FNCNE_ESPCL_P21)
      REFERENCES D02TBP21_FNCEESPCL (NU_FNCNE_ESPECIAL)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP16_CIFPRPRE
   ADD CONSTRAINT D021FP16 FOREIGN KEY (NU_PRODUTO_P20, NU_PRPRE_PRDTO_P20)
      REFERENCES D02TBP20_PRPREDSTO (NU_PRODUTO_O28, NU_PRPRE_PRDTO_O28)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP16_CIFPRPRE
   ADD CONSTRAINT D022FP16 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE D02TBP18_CIFATRBO
   ADD CONSTRAINT D021FP18 FOREIGN KEY (NU_GRUPO_CMNDO_P15, NU_ATRIBUTO_P19)
      REFERENCES D02TBP19_GRPOATRBO (NU_GRUPO_CMNDO_P04, NU_ATRIBUTO_P17)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP18_CIFATRBO
   ADD CONSTRAINT D022FP18 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE D02TBP19_GRPOATRBO
   ADD CONSTRAINT D021FP19 FOREIGN KEY (NU_GRUPO_CMNDO_P04)
      REFERENCES D02TBP04_GRPOCMNDO (NU_GRUPO_COMANDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP19_GRPOATRBO
   ADD CONSTRAINT D022FP19 FOREIGN KEY (NU_ATRIBUTO_P17)
      REFERENCES D02TBP17_ATRIBUTO (NU_ATRIBUTO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP20_PRPREDSTO
   ADD CONSTRAINT D022FP20 FOREIGN KEY (NU_PRODUTO_O28)
      REFERENCES D02TBP53_PRDTODSTO (NU_PRODUTO_O10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP23_MSGMSSTMA
   ADD CONSTRAINT D021FP23 FOREIGN KEY (CO_TPO_MSG_SSA_P22)
      REFERENCES D02TBP22_TPMSGMSSA (CO_TPO_MNSGM_SSTMA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP26_CMPTOFNCE
   ADD CONSTRAINT D021FP26 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP26_CMPTOFNCE
   ADD CONSTRAINT D022FP26 FOREIGN KEY (NU_FNCNE_ESPCL_P21)
      REFERENCES D02TBP21_FNCEESPCL (NU_FNCNE_ESPECIAL)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP26_CMPTOFNCE
   ADD CONSTRAINT D023FP26 FOREIGN KEY (NU_NIVEL_ALCDA_P54)
      REFERENCES D02TBP54_NVLALCDA (NU_NIVEL_ALCADA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP29_CIFCANAL
   ADD CONSTRAINT D021FP29 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE D02TBP29_CIFCANAL
   ADD CONSTRAINT D022FP29 FOREIGN KEY (NU_CANAL_CMRCO_P31)
      REFERENCES D02TBP31_CANAL (NU_CANAL_CMRCO_O15)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP30_CIFSSTMA
   ADD CONSTRAINT D021FP30 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE D02TBP30_CIFSSTMA
   ADD CONSTRAINT D022FP30 FOREIGN KEY (NU_SGMNO_ORGM_P24)
      REFERENCES D02TBP24_PRMOSSTMA (NU_SGMNO_ORGM_S12)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP32_CIFAGRDO
   ADD CONSTRAINT D021FP32 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP32_CIFAGRDO
   ADD CONSTRAINT D022FP32 FOREIGN KEY (NU_ACAO_AGRDO_P15, NU_MODO_AGRDO_P15, NU_GRUPO_AGRDO_P15, NU_SBGRO_AGRDO_P15, NU_TIPO_AGRDO_P15, NU_SBTPO_AGRDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP34_HSOCIFPRE
   ADD CONSTRAINT D021FP34 FOREIGN KEY (NU_ACAO_TRNSO_P16, NU_MODO_TRNSO_P16, NU_GRUPO_CMNDO_P16, NU_SBGRO_CMNDO_P16, NU_TIPO_CMNDO_P16, NU_SBTPO_CMNDO_P16, NU_PRODUTO_P16, NU_PRPRE_PRDTO_P16)
      REFERENCES D02TBP16_CIFPRPRE (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15, NU_PRODUTO_P20, NU_PRPRE_PRDTO_P20)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP41_CMPTOSTCO
   ADD CONSTRAINT D021FP41 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP41_CMPTOSTCO
   ADD CONSTRAINT D022FP41 FOREIGN KEY (NU_SITUACAO_P37)
      REFERENCES D02TBP37_STCOCTRTO (NU_SITUACAO_CTRTO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP42_CIFTDCL
   ADD CONSTRAINT D021FP42 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP42_CIFTDCL
   ADD CONSTRAINT D022FP42 FOREIGN KEY (NU_TD_P43, NU_CL_P43, NU_TIPO_TDCL_P43, NU_DIA_TDCL_P43)
      REFERENCES D02TBP43_TDCL (NU_TD, NU_CL, NU_TIPO_TDCL, NU_DIA_TDCL)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP44_ARQVORCBO
   ADD CONSTRAINT D022FP44 FOREIGN KEY (CO_TPO_MSG_SSA_P23, NU_MNSGM_SSTMA_P23)
      REFERENCES D02TBP23_MSGMSSTMA (CO_TPO_MSG_SSA_P22, NU_MNSGM_SISTEMA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP46_COLUNA
   ADD CONSTRAINT D021FP46 FOREIGN KEY (NO_TABELA_P45)
      REFERENCES D02TBP45_TABELA (NO_TABELA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP47_CONTEUDO
   ADD CONSTRAINT D021FP47 FOREIGN KEY (NO_COLUNA_P46, NO_TABELA_P46)
      REFERENCES D02TBP46_COLUNA (NO_COLUNA, NO_TABELA_P45)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP49_CIFTPOSDO
   ADD CONSTRAINT D021FP49 FOREIGN KEY (NU_TIPO_SALDO_P48)
      REFERENCES D02TBP48_TIPOSALDO (NU_TIPO_SALDO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP49_CIFTPOSDO
   ADD CONSTRAINT D022FP49 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP51_ITEMPRMTO
   ADD CONSTRAINT D021FP51 FOREIGN KEY (NU_PRMTO_CNTLE_P50)
      REFERENCES D02TBP50_PRMOCNTLE (NU_PARAMETRO_CNTLE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP56_CIFFNCNE
   ADD CONSTRAINT D021FP56 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP56_CIFFNCNE
   ADD CONSTRAINT D022FP56 FOREIGN KEY (NU_FNCNE_ESPCL_P21)
      REFERENCES D02TBP21_FNCEESPCL (NU_FNCNE_ESPECIAL)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP58_STCOMTVO
   ADD CONSTRAINT D021FP58 FOREIGN KEY (NU_SITUACAO_P37)
      REFERENCES D02TBP37_STCOCTRTO (NU_SITUACAO_CTRTO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP58_STCOMTVO
   ADD CONSTRAINT D022FP58 FOREIGN KEY (NU_MOTIVO_P57)
      REFERENCES D02TBP57_MTVOCTRTO (NU_MOTIVO_CTRTO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP61_CRGRAPSSO
   ADD CONSTRAINT D021FP61 FOREIGN KEY (NU_COREOGRAFIA_P59)
      REFERENCES D02TBP59_CRGRA (NU_COREOGRAFIA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP61_CRGRAPSSO
   ADD CONSTRAINT D022FP61 FOREIGN KEY (CO_PASSO_P60)
      REFERENCES D02TBP60_PASSO (CO_PASSO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP62_FLXOCRGRA
   ADD CONSTRAINT D021FP62 FOREIGN KEY (NU_COREOGRAFIA_P61, CO_PASSO_P61)
      REFERENCES D02TBP61_CRGRAPSSO (NU_COREOGRAFIA_P59, CO_PASSO_P60)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP62_FLXOCRGRA
   ADD CONSTRAINT D022FP62 FOREIGN KEY (NU_COREOGRAFIA_P61, CO_PRXMO_PASSO_P61)
      REFERENCES D02TBP61_CRGRAPSSO (NU_COREOGRAFIA_P59, CO_PASSO_P60)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP63_CIFCRGRA
   ADD CONSTRAINT D021FP63 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP63_CIFCRGRA
   ADD CONSTRAINT D022FP63 FOREIGN KEY (NU_COREOGRAFIA_P59)
      REFERENCES D02TBP59_CRGRA (NU_COREOGRAFIA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP63_CIFCRGRA
   ADD CONSTRAINT D023FP63 FOREIGN KEY (NU_SGMNO_ORGM_P24)
      REFERENCES D02TBP24_PRMOSSTMA (NU_SGMNO_ORGM_S12)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP64_CMPTOSTCO
   ADD CONSTRAINT D021FP64 FOREIGN KEY (NU_ACAO_TRNSO_P15, NU_MODO_TRNSO_P15, NU_GRUPO_CMNDO_P15, NU_SBGRO_CMNDO_P15, NU_TIPO_CMNDO_P15, NU_SBTPO_CMNDO_P15)
      REFERENCES D02TBP15_CIF (NU_ACAO_TRNSO_P14, NU_MODO_TRNSO_P14, NU_GRUPO_CMNDO_P10, NU_SBGRO_CMNDO_P10, NU_TIPO_CMNDO_P10, NU_SBTPO_CMNDO_P10)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP64_CMPTOSTCO
   ADD CONSTRAINT D022FP64 FOREIGN KEY (NU_SITUACAO_P58, NU_MOTIVO_P58)
      REFERENCES D02TBP58_STCOMTVO (NU_SITUACAO_P37, NU_MOTIVO_P57)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP65_ARQVORCBO
   ADD CONSTRAINT D021FP65 FOREIGN KEY (NU_SGMNO_ORGM_P24)
      REFERENCES D02TBP24_PRMOSSTMA (NU_SGMNO_ORGM_S12)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE D02TBP65_ARQVORCBO
   ADD CONSTRAINT D022FP65 FOREIGN KEY (CO_TPO_MSG_SSA_P23, NU_MNSGM_SSTMA_P23)
      REFERENCES D02TBP23_MSGMSSTMA (CO_TPO_MSG_SSA_P22, NU_MNSGM_SISTEMA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE DATABASE D08DB001;

CREATE DATABASE D02DB001;

